services:
  postgres:
    deploy:
      replicas: 1
    image: postgres:16
    ports:
      - "0.0.0.0:${DATABASE_PORT}:5432"
    volumes:
      - "$HOME/umami/data:/var/lib/postgresql/data"
      - "${APP_DIR}/docker/postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
    env_file:
      - .env.production
